version: "3"
services:
  samba:
    build: ./samba
    tty: true
    container_name: samba
    environment:
      - TZ=EST5EDT
    ports:
      - 139:139
      - 445:445
    command: '-u "admin;admin" -u "user1;xpto" -u "user2;xpto" -p'
    volumes: 
      - ./priv:/priv:z
      - ./pub:/pub:z
      - ./usr1:/usr1:z
      - ./usr2:/usr2:z
      - ./cfg/samba/smb.conf:/etc/samba/smb.conf:ro
